Changed rate change validatin + add validation for amount out
novasamatech/nova-wallet-android pull request #1196
Opened 2023-11-02 14:48 UTC by antonijzelinskij

#86931508w
I also fixed the case where `amountIn` was being rounded to zero in `amountOut` by adding a positiveAmount validation for `amountOut` and changing the field validator.
<img src="https://github.com/novasamatech/nova-wallet-android/assets/107959809/6a1f1a0f-c39a-458c-8d01-6a39b1cc9d08" width="260"/>

2023-11-02 14:48 UTC, stepanLav commented
Task linked: [CU-86931508w Android: Change slippage validation](https://app.clickup.com/t/86931508w)

2023-11-03 05:04 UTC, valentunn requested changes

2023-11-03 05:04 UTC, valentunn commented on feature-swap-impl/src/main/java/io/novafoundation/nova/feature_swap_impl/domain/validation/validations/SwapRateChangesValidation.kt
> +}
The idea was a little bit different - we should not use division here but rather just compare `quotedBalance` with either `amountOutMin` or `amountInMax`

2023-11-08 07:12 UTC, valentunn approved these changes

2023-11-08 12:46 UTC, merged