Fixed click availability and fee update when changing origin
novasamatech/nova-wallet-android pull request #1214
Opened 2023-11-10 16:32 UTC by antonijzelinskij

#86933mr3v
#86933qf9e

2023-11-10 16:32 UTC, stepanLav commented
Task linked: [CU-86933qf9e Android. XCM from swap screen. Fee is not recalculated after origin change](https://app.clickup.com/t/86933qf9e)

2023-11-10 16:32 UTC, stepanLav commented
Task linked: [CU-86933mr3v Android. Can select source chain in xcms](https://app.clickup.com/t/86933mr3v)

2023-11-10 16:35 UTC, valentunn approved these changes

2023-11-10 16:35 UTC, valentunn commented on feature-wallet-api/src/main/java/io/novafoundation/nova/feature_wallet_api/presentation/mixin/fee/FeeLoaderMixin.kt
> +    invalidationSources: List<Flow<*>>,
 additionalInvalidationSources

2023-11-10 16:35 UTC, valentunn commented on feature-wallet-api/src/main/java/io/novafoundation/nova/feature_wallet_api/presentation/mixin/fee/FeeLoaderMixin.kt
> +        invalidationSources.accumulate()
We can do `merge()` which is a little bit simpler

2023-11-13 06:23 UTC, valentunn requested changes
I am imroving this PR since I've found that it is still possible for wrong fee to be displayed due to race conditions between `comissionFlowAsset` and fee calculation

2023-11-13 06:31 UTC, valentunn approved these changes

2023-11-13 13:26 UTC, merged